name: tonal
description: tonal

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# 插件官网：https://pub.flutter-io.cn
dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^0.1.3 # adds the Cupertino Icons font for iOS style icons
  # fluttertoast: ^4.0.1 #原生Toast插件 https://github.com/PonnamKarthik/FlutterToast
  # flutter_screenutil: ^1.1.0 # 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil

  # flutter_launcher_icons: ^0.7.5  # 启动图标 https://github.com/fluttercommunity/flutter_launcher_icons
  # flutter_native_splash: ^0.1.9 # android/ios闪屏页 flutter pub run flutter_native_splash:create https://github.com/henriquearthur/flutter_native_splash

  path_provider: ^1.6.9 # 路径管理 https://github.com/flutter/plugins/tree/master/packages/path_provider
  package_info: ^0.4.0+18 # 包信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  device_info: ^0.4.2+4 # 设备信息 https://github.com/flutter/plugins/tree/master/packages/device_info
  connectivity: ^0.4.8+6 # 网络状态 https://github.com/flutter/plugins/blob/master/packages/connectivity

  shared_preferences: ^0.5.7+3 # 共享参数  https://github.com/flutter/plugins/blob/master/packages/shared_preferences
  sqflite: ^1.3.0

  provider: ^4.1.2 # 状态管理 https://github.com/rrousselGit/provider
  fluro: ^1.6.3 # 路由框架 https://github.com/theyakka/fluro
  dio: ^3.0.9 # 网络库 https://github.com/flutterchina/dio
  cached_network_image: ^2.2.0+1 # 图片框架 https://github.com/Baseflow/flutter_cached_network_image
  permission_handler: ^5.0.0+hotfix.6 # 权限管理 https://github.com/Baseflow/flutter-permission-handler
  url_launcher: ^5.4.10 #打开url https://github.com/flutter/plugins/tree/master/packages/url_launcher

  event_bus: ^1.1.1 # 事件总线  https://github.com/marcojakob/dart-event-bus
  flustars: ^0.3.2 # 工具库 https://github.com/Sky24n/flustars

  # video_player: ^0.10.11+1 # 视频播放 https://github.com/flutter/plugins/tree/master/packages/video_player
  # flare_flutter: ^2.0.3 # 动画效果 https://github.com/2d-inc/Flare-Flutter
  # flutter_svg: 0.17.4 # svg加载 https://github.com/dnfield/flutter_svg

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/images/splash.png
#  # android_disable_fullscreen: true # 禁用android全屏启动
#  fill: true # android下占满

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Gotham-Book
      fonts:
        - asset: fonts/Gotham-Book.otf
        - asset: fonts/Gotham-Book.otf
          style: italic
        - asset: fonts/Gotham-Book.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
